// Main page document schema with flexible component builder

export default {
  name: 'page',
  title: 'Pages',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Page Title',
      type: 'string',
      validation: Rule => Rule.required(),
      description: 'Internal title for the page',
    },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: Rule => Rule.required(),
      description: 'URL path for this page (e.g., "about" for /about)',
    },
    {
      name: 'metaTitle',
      title: 'Meta Title (SEO)',
      type: 'string',
      description: 'Title shown in search results and browser tabs',
      validation: Rule => Rule.max(60),
    },
    {
      name: 'metaDescription',
      title: 'Meta Description (SEO)',
      type: 'text',
      rows: 3,
      description: 'Description shown in search results',
      validation: Rule => Rule.max(160),
    },
    {
      name: 'template',
      title: 'Page Template',
      type: 'string',
      options: {
        list: [
          { title: 'Custom (Build with Components)', value: 'custom' },
          { title: 'Home Page', value: 'home' },
          { title: 'About Page', value: 'about' },
          { title: 'Services Page', value: 'services' },
          { title: 'Contact Page', value: 'contact' },
        ],
      },
      initialValue: 'custom',
      description: 'Use a template or build custom with components below',
    },
    {
      name: 'components',
      title: 'Page Components',
      type: 'array',
      of: [
        { type: 'heroComponent' },
        { type: 'identityQuoteComponent' },
        { type: 'philosophySectionComponent' },
        { type: 'focusAreasComponent' },
        { type: 'headshotProfileComponent' },
        { type: 'personalStatementComponent' },
        { type: 'textContentComponent' },
        { type: 'ctaButtonComponent' },
        { type: 'imageGalleryComponent' },
        { type: 'spacerComponent' },
        { type: 'previewScrollComponent' },
        { type: 'profileSectionComponent' },
        { type: 'consultationFormComponent' },
        { type: 'consultationFormWideComponent' },
        { type: 'heroV3Component' },
        { type: 'pullQuoteV3Component' },
        { type: 'whoIHelpV3Component' },
        { type: 'theSpaceV3Component' },
        { type: 'expressiveV3Component' },
        { type: 'meetV3Component' },
        { type: 'feelingsCheckInV3Component' },
        { type: 'ctaV3Component' },
      ],
      description: 'Add and arrange components to build your page',
      hidden: ({ document }) => document?.template !== 'custom',
    },
    {
      name: 'showHeader',
      title: 'Show Site Header',
      type: 'boolean',
      initialValue: true,
      description: 'Display the site header/navigation',
    },
    {
      name: 'showFooter',
      title: 'Show Site Footer',
      type: 'boolean',
      initialValue: true,
      description: 'Display the site footer',
    },
    {
      name: 'published',
      title: 'Published',
      type: 'boolean',
      initialValue: false,
      description: 'Make this page visible on the website',
    },
    {
      name: 'publishedAt',
      title: 'Published Date',
      type: 'datetime',
      description: 'When this page was published',
    },
  ],
  orderings: [
    {
      title: 'Title, A-Z',
      name: 'titleAsc',
      by: [{ field: 'title', direction: 'asc' }],
    },
    {
      title: 'Published Date, New',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      slug: 'slug.current',
      published: 'published',
      template: 'template',
    },
    prepare({ title, slug, published, template }) {
      return {
        title: title,
        subtitle: `/${slug || 'no-slug'} • ${template} ${published ? '✓' : '(draft)'}`,
      };
    },
  },
};
